const playersData = {
  "legends": [
    {"id":1,"name":"رونالدو (البرازيلي)","position":"هجوم","attack":98,"defense":45,"speed":92,"image":"ronaldo.png"},
    {"id":2,"name":"ميسي","position":"هجوم","attack":99,"defense":40,"speed":88,"image":"messi.png"},
    {"id":3,"name":"مارادونا","position":"هجوم","attack":97,"defense":38,"speed":85,"image":"maradona.png"},
    {"id":4,"name":"بيليه","position":"هجوم","attack":96,"defense":42,"speed":87,"image":"pele.png"},
    {"id":5,"name":"زيدان","position":"وسط","attack":90,"defense":70,"speed":78,"image":"zidane.png"},
    {"id":6,"name":"رونالدينيو","position":"وسط","attack":92,"defense":35,"speed":89,"image":"ronaldinho.png"},
    {"id":7,"name":"كاكا","position":"وسط","attack":88,"defense":50,"speed":86,"image":"kaka.png"},
    {"id":8,"name":"مودريتش","position":"وسط","attack":85,"defense":72,"speed":75,"image":"modric.png"},
    {"id":9,"name":"اينييستا","position":"وسط","attack":86,"defense":65,"speed":78,"image":"iniesta.png"},
    {"id":10,"name":"تشافي","position":"وسط","attack":84,"defense":70,"speed":70,"image":"xavi.png"},
    {"id":11,"name":"مالدييني","position":"دفاع","attack":60,"defense":96,"speed":80,"image":"maldini.png"},
    {"id":12,"name":"بويول","position":"دفاع","attack":55,"defense":95,"speed":75,"image":"puyol.png"},
    {"id":13,"name":"راموس","position":"دفاع","attack":75,"defense":92,"speed":78,"image":"ramos.png"},
    {"id":14,"name":"كانافارو","position":"دفاع","attack":50,"defense":94,"speed":76,"image":"cannavaro.png"},
    {"id":15,"name":"نيستا","position":"دفاع","attack":48,"defense":95,"speed":74,"image":"nesta.png"},
    {"id":16,"name":"روبرتو كارلوس","position":"دفاع","attack":82,"defense":78,"speed":90,"image":"carlos.png"},
    {"id":17,"name":"كافو","position":"دفاع","attack":70,"defense":85,"speed":88,"image":"cafu.png"},
    {"id":18,"name":"ياشين","position":"حارس","attack":30,"defense":97,"speed":40,"image":"yashin.png"},
    {"id":19,"name":"بوفون","position":"حارس","attack":28,"defense":96,"speed":35,"image":"buffon.png"},
    {"id":20,"name":"كاسياس","position":"حارس","attack":25,"defense":95,"speed":38,"image":"casillas.png"},
    {"id":21,"name":"نوير","position":"حارس","attack":40,"defense":94,"speed":50,"image":"neuer.png"},
    {"id":22,"name":"كريستيانو رونالدو","position":"هجوم","attack":97,"defense":48,"speed":91,"image":"cristiano.png"},
    {"id":23,"name":"توتي","position":"هجوم","attack":90,"defense":30,"speed":72,"image":"totti.png"},
    {"id":24,"name":"هنري","position":"هجوم","attack":93,"defense":35,"speed":90,"image":"henry.png"},
    {"id":25,"name":"باتيستوتا","position":"هجوم","attack":94,"defense":28,"speed":76,"image":"batistuta.png"},
    {"id":26,"name":"ماثيوس","position":"وسط","attack":82,"defense":80,"speed":76,"image":"matthaus.png"},
    {"id":27,"name":"بيكهام","position":"وسط","attack":85,"defense":55,"speed":74,"image":"beckham.png"},
    {"id":28,"name":"جيرارد","position":"وسط","attack":84,"defense":78,"speed":72,"image":"gerrard.png"},
    {"id":29,"name":"تيري","position":"دفاع","attack":50,"defense":93,"speed":70,"image":"terry.png"},
    {"id":30,"name":"فيديش","position":"دفاع","attack":45,"defense":92,"speed":68,"image":"vidic.png"}
  ],
  "normals": [
    {"id":31,"name":"الشناوي","position":"حارس","attack":20,"defense":85,"speed":30,"image":"default.png"},
    {"id":32,"name":"أونانا","position":"حارس","attack":25,"defense":83,"speed":35,"image":"default.png"},
    {"id":33,"name":"ميندي","position":"حارس","attack":22,"defense":84,"speed":32,"image":"default.png"},
    {"id":34,"name":"دي خيا","position":"حارس","attack":20,"defense":86,"speed":28,"image":"default.png"},
    {"id":35,"name":"شيزني","position":"حارس","attack":18,"defense":82,"speed":30,"image":"default.png"},
    {"id":36,"name":"لوريس","position":"حارس","attack":21,"defense":84,"speed":33,"image":"default.png"},
    {"id":37,"name":"ماجواير","position":"دفاع","attack":55,"defense":80,"speed":30,"image":"default.png"},
    {"id":38,"name":"كوليبالي","position":"دفاع","attack":50,"defense":88,"speed":65,"image":"default.png"},
    {"id":39,"name":"دي ليخت","position":"دفاع","attack":52,"defense":87,"speed":68,"image":"default.png"},
    {"id":40,"name":"أراوخو","position":"دفاع","attack":48,"defense":89,"speed":72,"image":"default.png"},
    {"id":41,"name":"كيم مين جاي","position":"دفاع","attack":45,"defense":88,"speed":70,"image":"default.png"},
    {"id":42,"name":"كيل ووكر","position":"دفاع","attack":70,"defense":82,"speed":88,"image":"default.png"},
    {"id":43,"name":"تريبيير","position":"دفاع","attack":72,"defense":80,"speed":75,"image":"default.png"},
    {"id":44,"name":"دومفريس","position":"دفاع","attack":68,"defense":78,"speed":82,"image":"default.png"},
    {"id":45,"name":"ديفيز","position":"دفاع","attack":65,"defense":76,"speed":85,"image":"default.png"},
    {"id":46,"name":"تيو هيرنانديز","position":"دفاع","attack":72,"defense":74,"speed":86,"image":"default.png"},
    {"id":47,"name":"أرنولد","position":"دفاع","attack":78,"defense":75,"speed":80,"image":"default.png"},
    {"id":48,"name":"كوكوريلا","position":"دفاع","attack":62,"defense":79,"speed":78,"image":"default.png"},
    {"id":49,"name":"برونو فيرنانديز","position":"وسط","attack":86,"defense":60,"speed":72,"image":"default.png"},
    {"id":50,"name":"كامافينغا","position":"وسط","attack":70,"defense":78,"speed":76,"image":"default.png"},
    {"id":51,"name":"تشواميني","position":"وسط","attack":72,"defense":80,"speed":74,"image":"default.png"},
    {"id":52,"name":"ماك أليستر","position":"وسط","attack":78,"defense":72,"speed":70,"image":"default.png"},
    {"id":53,"name":"سوبوسزلاي","position":"وسط","attack":80,"defense":65,"speed":76,"image":"default.png"},
    {"id":54,"name":"أوديغارد","position":"وسط","attack":84,"defense":55,"speed":74,"image":"default.png"},
    {"id":55,"name":"جوندوجان","position":"وسط","attack":82,"defense":68,"speed":70,"image":"default.png"},
    {"id":56,"name":"كوفاسيتش","position":"وسط","attack":76,"defense":74,"speed":72,"image":"default.png"},
    {"id":57,"name":"جريليش","position":"هجوم","attack":82,"defense":40,"speed":76,"image":"default.png"},
    {"id":58,"name":"ساكا","position":"هجوم","attack":85,"defense":42,"speed":80,"image":"default.png"},
    {"id":59,"name":"نيمار","position":"هجوم","attack":90,"defense":35,"speed":84,"image":"default.png"},
    {"id":60,"name":"ديمبيلي","position":"هجوم","attack":83,"defense":38,"speed":88,"image":"default.png"}
  ],
  "veryWeak": [
    {"id":61,"name":"مصطفى (ضعيف)","position":"هجوم","attack":15,"defense":12,"speed":18,"image":"default.png"},
    {"id":62,"name":"محمد (ضعيف)","position":"هجوم","attack":18,"defense":14,"speed":20,"image":"default.png"},
    {"id":63,"name":"علي (ضعيف)","position":"هجوم","attack":12,"defense":10,"speed":22,"image":"default.png"},
    {"id":64,"name":"حسن (ضعيف)","position":"وسط","attack":20,"defense":18,"speed":16,"image":"default.png"},
    {"id":65,"name":"سامي (ضعيف)","position":"وسط","attack":16,"defense":22,"speed":14,"image":"default.png"},
    {"id":66,"name":"مروان (ضعيف)","position":"وسط","attack":14,"defense":16,"speed":18,"image":"default.png"},
    {"id":67,"name":"إبراهيم (ضعيف)","position":"دفاع","attack":12,"defense":20,"speed":15,"image":"default.png"},
    {"id":68,"name":"يوسف (ضعيف)","position":"دفاع","attack":15,"defense":18,"speed":12,"image":"default.png"},
    {"id":69,"name":"عمر (ضعيف)","position":"دفاع","attack":10,"defense":22,"speed":14,"image":"default.png"},
    {"id":70,"name":"خالد (ضعيف)","position":"حارس","attack":8,"defense":15,"speed":10,"image":"default.png"},
    {"id":71,"name":"طارق (ضعيف)","position":"حارس","attack":6,"defense":18,"speed":8,"image":"default.png"},
    {"id":72,"name":"سعيد (ضعيف)","position":"حارس","attack":10,"defense":14,"speed":12,"image":"default.png"},
    {"id":73,"name":"جمال (ضعيف)","position":"هجوم","attack":22,"defense":10,"speed":16,"image":"default.png"},
    {"id":74,"name":"فايز (ضعيف)","position":"هجوم","attack":14,"defense":18,"speed":20,"image":"default.png"},
    {"id":75,"name":"نادر (ضعيف)","position":"وسط","attack":18,"defense":14,"speed":22,"image":"default.png"},
    {"id":76,"name":"رامي (ضعيف)","position":"وسط","attack":12,"defense":20,"speed":16,"image":"default.png"},
    {"id":77,"name":"شادي (ضعيف)","position":"دفاع","attack":8,"defense":25,"speed":12,"image":"default.png"},
    {"id":78,"name":"بلال (ضعيف)","position":"دفاع","attack":16,"defense":14,"speed":18,"image":"default.png"},
    {"id":79,"name":"حامد (ضعيف)","position":"حارس","attack":12,"defense":12,"speed":10,"image":"default.png"},
    {"id":80,"name":"رؤوف (ضعيف)","position":"حارس","attack":10,"defense":16,"speed":8,"image":"default.png"}
  ],
  "coaches": [
    {"name":"بيب جوارديولا","bonus":15,"type":"legend"},
    {"name":"كارلو أنشيلوتي","bonus":12,"type":"legend"},
    {"name":"زين الدين زيدان","bonus":10,"type":"legend"},
    {"name":"يورغن كلوب","bonus":12,"type":"legend"},
    {"name":"رانجنيك","bonus":5,"type":"normal"},
    {"name":"أنطونيو كونتي","bonus":6,"type":"normal"},
    {"name":"ماسيميليانو أليجري","bonus":4,"type":"normal"},
    {"name":"ماوريسيو بوكيتينو","bonus":5,"type":"normal"}
  ],
  "formations": {
    "4-3-3": {"goalkeeper":1,"defenders":4,"midfielders":3,"attackers":3},
    "4-4-2": {"goalkeeper":1,"defenders":4,"midfielders":4,"attackers":2},
    "3-5-2": {"goalkeeper":1,"defenders":3,"midfielders":5,"attackers":2}
  }
};